package com.interviewprep.orders.springapp.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The persistence-ready evolution of {@code java-basics}' {@code Customer}
 * record.
 *
 * ============================================================================
 * WHY THIS IS A MUTABLE CLASS WITH A NO-ARG CONSTRUCTOR, NOT A RECORD
 * (read this once — every entity in this package follows the same reasoning,
 * so later files just point back here):
 * ============================================================================
 *
 * 1. NO-ARG CONSTRUCTOR REQUIREMENT: Hibernate (the JPA provider Spring Boot
 *    wires up by default) builds entity instances via reflection when
 *    hydrating rows from a `ResultSet` — it calls a no-arg constructor and
 *    then sets each field directly (or via a generated proxy), rather than
 *    calling a fully-parameterized constructor with the exact right argument
 *    order at exactly the point a row is read. A record's ONLY constructor
 *    is generated from its component list — there is no way to add a
 *    separate no-arg constructor to a record while keeping the compact
 *    canonical one, so records are fundamentally the wrong shape here.
 *    (Some JPA providers/newer specs have limited support for records as
 *    read-only/immutable projections — see the DTO discussion below for why
 *    that's a different, narrower use case than a full entity.)
 *
 * 2. MUTABLE STATE / IDENTITY VIA GENERATED ID: a record's whole point is
 *    value semantics — two records with equal fields ARE equal, with no
 *    independent identity. A JPA entity is the opposite: identity comes from
 *    its primary key ({@code id}, generated by the database), and two
 *    `Customer` rows with identical name/email are still two different
 *    customers if they have different ids. Hibernate also needs to mutate
 *    fields after construction (setting the generated `id` post-insert,
 *    lazy-loading a collection into a field later) — a record's fields are
 *    all `private final`, which makes this impossible without reflection
 *    hacks Hibernate doesn't use for record components today.
 *
 * 3. PROXYING FOR LAZY LOADING: Hibernate often returns a runtime-generated
 *    subclass (a "proxy") standing in for an entity that hasn't been loaded
 *    from the DB yet, so `@ManyToOne`/`@OneToMany` associations can be
 *    fetched lazily on first access. Subclassing requires a non-final class
 *    with an accessible (no-arg) constructor — records are implicitly
 *    `final` and cannot be subclassed at all.
 *
 * This is a genuinely common senior-interview question ("why can't you use
 * a record as a JPA entity?") — the answer above (no-arg ctor, mutable
 * identity-bearing state, proxying) is the complete one; "records are
 * immutable" alone is true but incomplete.
 *
 * Continuity note: this class models the exact same real-world concept as
 * java-basics' {@code Customer} record — a person placing orders — just
 * with the shape a relational persistence layer requires. Treat this as
 * "Customer, the persistence-ready evolution," not an unrelated new class.
 */
@Entity
@Table(name = "customers", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Customer {

    /**
     * SURROGATE KEY (a DB-generated, meaningless-outside-the-DB identifier)
     * vs. a NATURAL KEY (e.g. email, which has real-world meaning). Using a
     * surrogate {@code Long id} here — generated via {@code IDENTITY}
     * (delegates to the DB's auto-increment/serial column; simplest option,
     * costs one round-trip per insert since Hibernate can't pre-fetch a
     * batch of ids) rather than {@code SEQUENCE} (a DB sequence Hibernate
     * CAN pre-allocate in batches, better for high insert-throughput, but
     * needs the DB to support sequences — Postgres does, plain MySQL
     * historically didn't) — is the standard pattern because natural keys
     * can change (a customer's email changes) and identity should never
     * change once assigned. See EXPLANATION.md for the IDENTITY vs SEQUENCE
     * trade-off in more depth.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 120)
    private String name;

    @Column(nullable = false, unique = true, length = 254)
    private String email;

    /**
     * Bidirectional {@code @OneToMany}, mapped by the {@code customer} field
     * on {@code Order} (the "owning side" — it holds the foreign key column
     * `customer_id`). {@code Customer} is the "inverse side": it doesn't own
     * the relationship and changes here alone (without also updating
     * `order.setCustomer(this)`) would NOT be persisted — a classic JPA
     * gotcha covered in EXPLANATION.md.
     *
     * cascade = ALL + orphanRemoval intentionally NOT set here (unlike
     * Order -> OrderLine below): deleting a Customer should almost never
     * cascade-delete their Order history in a real system (financial/audit
     * requirements usually forbid losing order records) — that asymmetry
     * versus Order -> OrderLine (where cascade IS appropriate, because an
     * OrderLine has no meaning outside its Order) is itself an interview
     * point: cascade choices should follow the real-world lifecycle
     * dependency, not be applied uniformly "for convenience."
     */
    @OneToMany(mappedBy = "customer", fetch = FetchType.LAZY)
    private List<Order> orders = new ArrayList<>();

    /** Required by JPA — see the class Javadoc. Package-private is enough;
     * Hibernate uses reflection and never needs this to be public. */
    protected Customer() {
    }

    public Customer(String name, String email) {
        this.name = requireNonBlank(name, "name");
        this.email = requireValidEmail(email);
    }

    private static String requireNonBlank(String value, String field) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(field + " must not be blank");
        }
        return value;
    }

    private static String requireValidEmail(String email) {
        if (email == null || !email.contains("@")) {
            throw new IllegalArgumentException("email is invalid: " + email);
        }
        return email;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = requireNonBlank(name, "name");
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = requireValidEmail(email);
    }

    public List<Order> getOrders() {
        // Same defensive-copy discipline as java-basics' Order.getLines():
        // never hand out the live, mutable backing list.
        return List.copyOf(orders);
    }

    /**
     * EQUALS/HASHCODE ON A NATURAL KEY (email), NOT ON {@code id} OR "ALL
     * FIELDS": this is the Vlad-Mihalcea-recommended pattern for JPA
     * entities, and worth memorizing the reasoning for a senior interview:
     *
     * - Using {@code id} directly is unsafe because a transient (not-yet-
     *   persisted) entity has {@code id == null}; two different transient
     *   Customers would then wrongly compare equal (both null), and — worse
     *   — an entity's hashCode would CHANGE after being persisted (null ->
     *   generated id), which breaks the contract for any entity already
     *   placed in a {@code HashSet}/used as a {@code HashMap} key before
     *   being saved.
     * - Using Lombok's {@code @Data} (all-field equals/hashCode) is an
     *   anti-pattern on entities for the same reason PLUS it can trigger
     *   the lazy-loading of every association just to compute equality, and
     *   mutable fields changing over time silently change hash bucket
     *   placement.
     * - A stable natural/business key (here, {@code email}, which this
     *   class enforces is unique and non-null before construction even
     *   completes) gives consistent equality before AND after persistence.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Customer other)) {
            return false;
        }
        return Objects.equals(email, other.email);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(email);
    }

    @Override
    public String toString() {
        return "Customer[id=%s, name=%s, email=%s]".formatted(id, name, email);
    }
}
